--- 
jobs: 
  - 
    displayName: "Install Node.js"
    job: NodeTool@0
  - job: Build
    pool: 
      vmImage: "${{ parameters.vmImage }}"
    steps: 
      - script: "npm install"
      - script: "npm test"
      - displayName: "Archive files"
        inputs: 
          includeRootFolder: false
          rootFolderOrFile: $(System.DefaultWorkingDirectory)
      - task: ArchiveFiles@2
