
jobs: 
  
    job: NodeTool@0
  - job: Build
    pool: 
      vmImage: "${{ parameters.vmImage }}"
    steps: 
      - script: "npm install"
      - script: "npm test"
        inputs: 
          includeRootFolder: false
          rootFolderOrFile: $(System.DefaultWorkingDirectory)
      - task: ArchiveFiles@2
