parameters:
  vmImage: 'ubuntu 16.04'

jobs:
- job: NodeTool@0
  displayName: 'Install Node.js'
  
- job: Build
  pool:
    vmImage: ${{ parameters.vmImage }}
steps:
  - script: npm install
  - script: npm test
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      
- job: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
