parameters:
  vmImage: 'ubuntu 16.04'

jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: npm install
  - script: npm test
  - task: Npm@1
    inputs:
      command: publish
      publishRegistry: node-express-azure
      publishFeed: Artifacts
